version: '3'

volumes:
  production_traefik: {}
  production_postgres_data: {}
  production_postgres_data_backups: {}


services:

  voyant_gen:
    image: python:3
    volumes:
      - ./corpora:/corpora
      - ./input:/input
      - ./voyant_gen:/workdir
    command: python -u workdir/voyant_gen.py /input/keywords/keywords.txt /input/articles/ /corpora/

  voyant:
    build:
      context: .
      dockerfile: ./compose/voyant/Dockerfile
    image: voyant_app
    depends_on:
      - voyant_gen
    working_dir: /var/www/voyant
    command: java -jar VoyantServer.jar --headless=true

  traefik:
    build:
      context: .
      dockerfile: ./compose/traefik/Dockerfile
    image: voyant_traefik
    depends_on:
      - voyant
      - django
    volumes:
      - production_traefik:/etc/traefik/acme
      - ./corpora:/voyant/corpora
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"

  nginx:
    image: nginx:latest
    volumes:
      - ./corpora:/usr/share/nginx/html/corpora

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: static_page_proxy_production_django
    depends_on:
      - postgres
      - redis
      - jekyll_builder
    volumes:
      - ./static_pages:/app/proxy/templates/proxy
      - ./static_pages/assets:/app/proxy/static
      - ./input:/app/proxy/media
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: /start

  postgres:
    build:
      context: .
      dockerfile: ./compose/postgres/Dockerfile
    image: static_page_proxy_production_postgres
    volumes:
      - production_postgres_data:/var/lib/postgresql/data
      - production_postgres_data_backups:/backups
    env_file:
      - ./.envs/.production/.postgres

  redis:
    image: redis:5.0

  jekyll_builder:
    image: jekyll/jekyll:latest
    volumes:
      - ./ed:/srv/jekyll
      - ./static_pages:/destination
    command: jekyll build --watch --force_polling --incremental -d /destination

  text_to_md:
    image: python:3
    depends_on:
      - voyant_gen
    volumes:
      - ./ed:/ed
      - ./text_to_md:/workdir
      - ./corpora:/workdir/csvs
      - ./input:/input
    command: python workdir/text2md.py input/texts workdir/csvs ed/_texts
